### ISSUE TITLE
Token timeout/lifetime is ignored

### ISSUE THREAD

**Issue by adam-sse** [Student-Management-System/Rights-Management#8]
The daemon only logs in to the student management system once during startup. But over time, the token will be invalid (standard timeout is a few hours, AFAIK). After that time, all operations will fail with "unauthorized".

Proposed fix: The daemon regularly gets a new token. Ideally it would do this based on the actual lifetime of the token, but I don't know if we can get that information.

**Comment by Elscha** [comment]
Fixed by
* Student-Management-System/Submitter-Protocol@e422cefdc005e2706cf98545a60e557e77395a43
* Student-Management-System/Submitter-Protocol@d5a7f77a5b1b26105e66954f1dc80a81aefae003
* Student-Management-System/Submitter-Protocol@f914073935af9782777208c2b482c71dcbaaf0df
* Student-Management-System/Submitter-Protocol@4cd9f8f13d75e80b904501b87c85c6e8a9673519

Confirmed by @adam-sse that this really works on demo server.
